version: 0.1
log:
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /tmp/registry
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
proxy:
  remoteurl: https://hub.guazi-cloud.com
  username: admin
  password: Harbor12345
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
